config/routes.rb
Rails.application.routes.draw do
  resources :meals, except: :destroy

  # log in page with form:
	get '/login'     => 'sessions#new'

	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'

	# delete action to log out:
	delete '/logout' => 'sessions#destroy'

  root 'meals#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
require 'csv'

class Meal < ApplicationRecord
  belongs_to :user

  enum moment: {
    breakfast: 'breakfast',
    morning_snack: 'morning_snack',
    lunch: 'lunch',
    afternoon_snack: 'afternoon_snack',
    dinner: 'dinner'
  }

  validates :eaten_on, presence: true
  validates :moment, presence: true, uniqueness: { scope: :eaten_on, message: 'you already declared a meal for that moment' }
  validates :content, presence: true

  def self.to_csv
    attributes = %w{id eaten_on moment content}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |meal|
        csv << attributes.map{ |attr| meal.send(attr) }
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :meals

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  # Define the current_user method:
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_path, alert: 'You must be logged in to access this page.' if current_user.nil?
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :authorize
  before_action :set_meal, only: [:edit, :update]
  before_action :redirect_mobile_users, only: [:index]
  before_action :redirect_desktop_users, only: [:show]

  # GET /meals
  # GET /meals.json
  def index
    @day = params[:day].try { |str| Date.iso8601(str) } || Date.today
    @days = @day.at_beginning_of_week..@day.at_end_of_week
    @meals = Meal.where(user: current_user, eaten_on: @days)

    respond_to do |format|
      format.html
      format.csv { send_data @meals.order(:eaten_on).to_csv, filename: "meals-#{@day.cweek}.csv" }
    end
  end

  def show
    @day = Date.parse(params[:id])
    @meals = Meal.where(user: current_user, eaten_on: @day)
  end

  # GET /meals/new
  def new
    @meal = Meal.new()
    @meal.eaten_on = params[:eaten_on]
    @meal.moment = params[:moment]
  end

  # GET /meals/1/edit
  def edit
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(meal_params) do |m|
      m.user = current_user
    end

    respond_to do |format|
      if @meal.save
        format.html { redirect_to meals_path(day: @meal.eaten_on), notice: 'Meal was successfully created.' }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to  meals_path(day: @meal.eaten_on), notice: 'Meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal }
      else
        format.html { render :edit }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params.require(:meal).permit(:eaten_on, :content, :moment)
    end

    def redirect_mobile_users
      redirect_to meal_url(Date.today) if browser.device.mobile?
    end

    def redirect_desktop_users
      redirect_to meals_url(day: params[:id]) unless browser.device.mobile?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:login][:email].downcase)

    if user && user.authenticate(params[:login][:password])
      # Save the user.id in that user's session cookie:
      session[:user_id] = user.id.to_s
      redirect_to root_path, notice: 'Successfully logged in!'
    else
      # if email or password incorrect, re-render login page:
      flash.now.alert = "Incorrect email or password, try again."
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path, notice: "Logged out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyMeals</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-grey-lighter font-sans leading-normal tracking-normal">
    <div class="py-6 px-2">
      <%= yield %>
    </div>
  </body>
</html>

app/views/meals/_day_meals.html.erb
<% Meal.moments.each_value do |moment| %>
  <% meal = meals.find { |meal| meal.moment == moment } %>

  <div class="flex-1 p-2 md:m-2 bg-white rounded-sm shadow">
    <div class="flex items-end">
      <p class="uppercase text-grey-dark font-bold text-sm mr-2">
        <%= Meal.human_attribute_name("moment.#{moment}") %>
      </p>
      <% if meal %>
        <%= link_to edit_meal_path(meal), class: "text-indigo-dark" do %>
          <i class="fas fa-pen fa-sm"></i>
        <% end %>
      <% else %>
        <%= link_to new_meal_path(eaten_on: day, moment: moment), class: "text-indigo-dark" do %>
          <i class="fas fa-plus fa-sm"></i>
        <% end %>
      <% end %>
    </div>

    <div class="overflow-y-scroll <%= moment.include?('snack') ? 'h-12' : 'h-24' %>">
      <div class="text-xs">
        <% if meal %>
          <%= simple_format(meal.content) %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/meals/_form.html.erb
<div class="container mx-auto">
  <%= form_with(model: meal, local: true) do |form| %>
    <% if meal.errors.any? %>
      <div class="mb-4">
        <div class="flex bg-red-dark text-white text-sm font-bold px-4 py-3 rounded-sm shadow-md">
          <div class="mr-2">
            <i class="fas fa-exclamation-triangle fa-lg"></i>
          </div>
          <div>
            <p>This meal cannot be saved:</p>
            <ul>
              <% meal.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>

    <%= form.hidden_field :eaten_on %>
    <%= form.hidden_field :moment %>

    <div class="w-full mb-6">
      <%= form.label :content, class: "text-center block uppercase tracking-wide text-grey-darker text-xs font-bold mb-3" %>
      <%= form.text_area :content, rows: 10, autofocus: true, class: "appearance-none block w-full bg-white text-grey-darker border border-grey-lighter rounded-sm py-4 px-5 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-grey" %>
    </div>

    <div class="actions flex justify-between items-center">
      <%= link_to meals_path(day: @meal.eaten_on), class: "text-xs text-indigo-darker hover:text-indigo-darkest no-underline mr-2" do %>
        <i class="fas fa-arrow-left fa-fw"></i>
        <%= t('.back_label') %>
      <% end %>
      <%= form.submit class: "btn btn--indigo" %>
    </div>

  <% end %>
</div>

app/views/meals/edit.html.erb
<header class="mb-6">
  <h1 class="text-xl text-center font-semibold">
    Editing Meal
    <%= t('.title') %>
  </h1>
  <p class="text-sm text-grey-dark text-center">
    <%= time_tag @meal.eaten_on %> - <%= Meal.human_attribute_name("moment.#{@meal.moment}") %>
  </p>
</header>

<%= render 'form', meal: @meal %>

app/views/meals/index.html.erb
<header class="flex justify-center mb-6 items-center">
  <%= link_to meals_path(day: @day - 1.week), class: "text-indigo-dark px-3" do %>
    <i class="fas fa-chevron-left fa-lg"></i>
  <% end %>
  <div class="text-center px-3">
    <p class="text-xl font-semibold uppercase">
      <%= raw t('.title', from: time_tag(@day.at_beginning_of_week, format: :short), to: time_tag(@day.at_end_of_week, format: :short))  %>
    </p>
  </div>
  <%= link_to meals_path(day: @day + 1.week), class: "text-indigo-dark px-3" do %>
    <i class="fas fa-chevron-right fa-lg"></i>
  <% end %>
</header>

<nav class="container mx-auto mb-6">
  <div class="flex justify-around">
    <div class="flex-1"></div>
    <div class="flex-1 text-center">
      <%= link_to meals_path(day: @day, format: :csv), class: 'btn btn--green text-sm' do %>
        <i class="fas fa-download fa-fw"></i>
        <%= t('.export_csv_cta') %>
      <% end %>
    </div>
    <div class="flex-1 text-right">
      <%= link_to logout_path, method: :delete, class: 'text-red-dark text-sm hover:text-red-light' do %>
        <%= t('.signout_cta') %>
        <i class="fas fa-sign-out-alt fa-fw"></i>
      <% end %>
    </div>
  </div>
</nav>

<div class="px-2 overflow-x-scroll mb-6">
  <div>
    <% @days.each do |day| %>
      <% day_meals = @meals.select { |meal| meal.eaten_on == day } %>

      <div>
        <header class="text-left font-bold uppercase">
          <%= time_tag day, l(day, format: "%A") %>
        </header>

        <div class="flex flex-row -mx-2">
          <%= render "day_meals", meals: day_meals, day: day %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/meals/new.html.erb
<header class="mb-6">
  <h1 class="text-xl text-center font-semibold">
    <%= t('.title') %>
  </h1>
  <p class="text-sm text-grey-dark text-center">
    <%= time_tag @meal.eaten_on %> - <%= Meal.human_attribute_name("moment.#{@meal.moment}") %>
  </p>
</header>

<%= render 'form', meal: @meal %>

app/views/meals/show.html.erb
<nav class="flex justify-center items-center mb-6">
  <%= link_to meal_path(@day - 1.day), class: "text-indigo-dark px-3" do %>
    <i class="fas fa-chevron-left fa-lg"></i>
  <% end %>
  <div class="text-center uppercase">
    <p>
      <%= time_tag @day, class: "text-xl font-semibold px-3" %>
    </p>
  </div>
  <%= link_to meal_path(@day + 1.day), class: "text-indigo-dark px-3" do %>
    <i class="fas fa-chevron-right fa-lg"></i>
  <% end %>
</nav>

<% if notice %>
  <div class="mb-4">
    <div class="flex items-center bg-green text-white text-sm font-bold px-4 py-3">
      <i class="fas fa-check w-4 h-4 mr-2"></i>
      <p><%= notice %></p>
    </div>
  </div>
<% end %>


<%= link_to logout_path, method: :delete, class: 'fixed pin-b pin-r mr-4 mb-4 rounded-full h-12 w-12 flex items-center justify-center bg-red-light text-white shadow-lg' do %>
  <i class="fas fa-sign-out-alt fa-lg"></i>
<% end %>

<div class="mb-16">
  <%= render "day_meals", meals: @meals, day: @day %>
</div>